---
name: unit-tests
on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: pull repo
        uses: actions/checkout@v3
      - name: setup python environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: configure python for tests
        run: |
          pip install pytest
      - name: run tests
        run: |
          pytest
